"""add_scan_metadata

Revision ID: 2a5834767597
Revises: 9bbc19263336
Create Date: 2026-05-28 07:41:51.353910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5834767597'
down_revision: Union[str, Sequence[str], None] = '9bbc19263336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('scans', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('scans', sa.Column('mime_type', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'mime_type')
    op.drop_column('scans', 'file_size')
    op.drop_column('scans', 'original_filename')
    # ### end Alembic commands ###
