"""add_studies_table

Revision ID: 2de5af170503
Revises: 2a5834767597
Create Date: 2026-05-29 16:36:07.776926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2de5af170503'
down_revision: Union[str, Sequence[str], None] = '2a5834767597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('study_date', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.add_column('scans', sa.Column('study_id', sa.String(length=100), nullable=True))
    op.add_column('scans', sa.Column('scan_type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'scans', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_column('scans', 'scan_type')
    op.drop_column('scans', 'study_id')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
